name: CI/CD
on:
  pull_request: 
    branches: [main]
    types: [opened, synchronize, reopened]
  push:
    branches: [ft/*, hf/*]

jobs:

  export-game:
    name: 'Export All Platforms'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Generate Version File
      run: |
        echo "alpha." > version.txt
    - name: Export Web Version
      uses: davidwesst/godot-mono-export@v3.2.3
      with:
        project-path: ./
        export-config: Web
        export-path: build/web/index.html
    - name: Export Windows Desktop Version
      uses: davidwesst/godot-mono-export@v3.2.3
      with:
        project-path: ./
        export-config: "Windows"
        export-path: build/windows-desktop/game.exe
    - name: Export Linux/X11 Desktop Version
      uses: davidwesst/godot-mono-export@v3.2.3
      with:
        project-path: ./
        export-config: "Linux/X11"
        export-path: build/linux-x11/game.x86_64
    - name: Archive Web Export
      uses: actions/upload-artifact@v2
      if: ${{ success() && github.ref == 'refs/heads/main' }}
      with:
        name: web
        path: build/web
    - name: Archive Windows Export
      uses: actions/upload-artifact@v2
      if: ${{ success() && github.ref == 'refs/heads/main' }}
      with:
        name: windows-desktop
        path: build/windows-desktop
    - name: Archive Linux/11 Export
      uses: actions/upload-artifact@v2
      if: ${{ success() && github.ref == 'refs/heads/main' }}
      with:
        name: linux-x11
        path: build/linux-x11

  publish-to-itchio:
    if: ${{ github.ref == 'refs/heads/ft/gh-actions' }}
    needs: [export-game]
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        path: artifacts/
    - name: Copy Version Files
      run: |
        ${GITHUB_SHA::8}.windows-desktop >> artifacts/windows-desktop/version.txt
        ${GITHUB_SHA::8}.linux-x11 >> artifacts/linux-x11/version.txt
        ${GITHUB_SHA::8}.web >> artifacts/web/version.txt
    - name: Publish Windows Build
      uses: davidwesst/butler-publish-itchio-action@master
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        CHANNEL: windows
        ITCH_GAME: testing-sandbox
        ITCH_USER: davidwesst
        PACKAGE: artifacts/windows-desktop
        VERSION_FILE: version.txt
    - name: Publish Linux/X11 Build
      uses: davidwesst/butler-publish-itchio-action@master
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        CHANNEL: linux_x11
        ITCH_GAME: testing-sandbox
        ITCH_USER: davidwesst
        PACKAGE: artifacts/linux-x11
        VERSION_FILE: version.txt
    - name: Publish Web Build
      uses: davidwesst/butler-publish-itchio-action@master
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        CHANNEL: linux_x11
        ITCH_GAME: testing-sandbox
        ITCH_USER: davidwesst
        PACKAGE: artifacts/web
        VERSION_FILE: version.txt
